### ISSUE TITLE
Decentralized Exchange - smart contract in ink!

### ISSUE THREAD

**Issue by TomaszWaszczyk** [PolkadotStudy/polkadot.study#17]
**Why would it help the Polkadot Dev Community**
I would be helpful for new developers in Substrate ecosystem to look at how decentralized exchange actually works.

**Tutorial Outline**
I want to extended [the repository](https://github.com/TomaszWaszczyk/ink-automated-market-maker) and make complete the smart contract and additionally write tutorial about mechanism behind.

I plan also implement user interface in Rust, but this is NOT the part of the tutorial.

**Checks**
You do not have to check all.

- [X] There is no similar tutorial already around somewhere
- [X] I want to receive funding and have not already received funding for the tutorial (after delivering)
- [X] The tutorial is not published yet
- [x] The tutorial is already published **add link**

**Deadline**
40 days, 03 Jul 2023

**Comment by niklasp** [comment]
published on July 7, 2023, transaction: https://kusama.subscan.io/extrinsic/0x095eb8322ce7955fbcf8f80e3d4120cf902f87712f7434e35cd6f95f81944a15
