### ISSUE TITLE
Add Manic Minter ink! tutorial

### ISSUE THREAD

**Issue by midegdugarova** [PolkadotStudy/polkadot.study#28]
**Why would it help the Polkadot Dev Community**
A short description of what common problems it solves.

We propose to publish an intermediate ink! tutorial. There are enough tutorials that cover basic ink! such as 'flipper' or 'Hello World' contracts, and we would like to share more intermediate-advanced content. Our tutorial includes cross-contract calling and ink! e2e testing framework. 

**Tutorial Outline**
A short outline on what you plan to write about. You can use bullet points.

- Creating a psp22 contract
- Creating a minter contract
- Create a psp22 contract refrence
- Perform cross-contract call to mint the psp22 from the minter
- Write e2e tests.

**Deadline**
July 21

**Checks**
You do not have to check all.

- [ + ] There is no similar tutorial alread around somewhere
- [ ] I want to receive funding and have not already received funding for the tutorial
- [ ] The tutorial is not published yet 
- [ + ] The tutorial is already published **https://docs.astar.network/docs/build/wasm/from-zero-to-ink-hero/manic-minter/**

**Comment by niklasp** [comment]
@midegdugarova ping

**Comment by niklasp** [comment]
@midegdugarova any update on this, how can I reach you to discuss the tutorial further?

**Comment by niklasp** [comment]
?

**Comment by niklasp** [comment]
closed due to inactivity
