### ISSUE TITLE
Add your parachain to the Polkadot Vault (aka Parity Signer)

### ISSUE THREAD

**Issue by prybalko** [PolkadotStudy/polkadot.study#6]
**Why would it help the Polkadot Dev Community**
It is a common use case for parachain developers to make Polkadot Vault support their chain.

**Tutorial Outline**

- Intro to Polkadot Vault
- Intro to chain metadata and metadata portal
- Host your own metadata portal
- Fetch chain specs and metadata
- Sign chain specs and metadata
- Add Polkadot Vault account to the PolkadotJs extension
- Sign transaction with your Polkadot Vault

**Checks**
You do not have to check all.

- [X] There is no similar tutorial already around somewhere
- [X] I want to receive funding and have not already received funding for the tutorial
- [X] The tutorial is not published yet
- [ ] The tutorial is already published **add link**

**Comment by niklasp** [comment]
published: https://polkadot.study/tutorials/parachain-to-polkadot-vault/intro

**Comment by niklasp** [comment]
payment: https://etherscan.io/tx/0x913e0a66f4c30d6454555b0264144d38e0fc3ca740d1f591ea2db40d9d9d8454
