### ISSUE TITLE
Basic wallet with Polkadot.js API and React with TypeScript.

### ISSUE THREAD

**Issue by A-mont** [PolkadotStudy/polkadot.study#7]
**Why would it help the Polkadot Dev Community**
Having a way to manage tokens on a blockchain is essential. This tutorial will help developers use the basic features of the Polkadot.js API in a real project using React with TypeScript.

**Tutorial Outline**

•	Introduction to using the Polkadot.js API with TypeScript.
•	Create a React project with TypeScript and install Polkadot.js API.
•	Create a graphical interface for Wallet with TypeScript.
•	Create new keys with the GUI using the Polkadot.js API.
•	Control and update balances on Polkadot and Kusama blockchains.
•	Transfer between wallet accounts.
•	Conclusion.

**Checks**
You do not have to check all.

- [x] There is no similar tutorial alread around somewhere
- [x] I want to receive funding and have not already received funding for the tutorial
- [x] The tutorial is not published yet
- [ ] The tutorial is already published **add link**

**Comment by niklasp** [comment]
Link to the review: https://docs.google.com/document/d/1dlkTKbd-IOxad7H2BabvPIUICb6laU_fmcQEDoF3o2Y/edit

**Comment by niklasp** [comment]
completed! https://polkadot.study/tutorials/wallet-with-polkadot-js-and-react-with-typescript/intro

**Comment by niklasp** [comment]
paid: 
1. https://kusama.subscan.io/extrinsic/17249140-2
2.https://kusama.subscan.io/extrinsic/0x17b3fdb0edb22b2bdbd428115b771ddadffe091f984bfa42619db00c26af35f7
