### ISSUE TITLE
Kitties Tutorial part 2

### ISSUE THREAD

**Issue by WalquerX** [PolkadotStudy/polkadot.study#8]
**Why would it help the Polkadot Dev Community**
I will guide the reader to create an extension to the kitties tutorial. So to include patterns that can be used as reference examples.

**Tutorial Outline**
- Update of kitties tutorial so to have it at version polkadot-v0.9.39 and add some explanations.
- How to add Scheduller pallet and automate a call execution.
- How to add Assets pallet so to sell kitties in native currency and tokens.
- How to writte unit test.
- How to do the benchmarking.
- How to configure the runtime so to compile the node.

**Checks**
You do not have to check all.

- [x] There is no similar tutorial alread around somewhere
- [x] I want to receive funding and have not already received funding for the tutorial
- [x] The tutorial is not published yet
- [ ] The tutorial is already published **add link**

**Comment by niklasp** [comment]
🎉  Great @WalquerX, looking forward to your tutorial. Please finish until Mid May so we can have it ready with the other tutorials end of May

**Comment by niklasp** [comment]
payments:
1. https://etherscan.io/tx/0x0515e73fbe4f06d6786ecb94edf7b60eb9d0c4ca5a144ebbc26fe6d8d73a0bf6

**Comment by chuacw** [comment]
Is this paid, but not done?

**Comment by niklasp** [comment]
it is done and will be merged soon
